const jq = require("jquery");
const jsdom = require("jsdom");
const getPage = require("../api/fetch").getPage;
const File = require("fs");
const Queue = require("../api/queue").Queue;

var a = ["BB霜",
        "乳液",
        "保湿",
        "化妆",
        "口红",
        "唇膏",
        "唇色",
        "底妆",
        "彩妆",
        "抗皱",
        "护唇",
        "护肤",
        "气垫",
        "油皮",
        "洁面",
        "洗头",
        "洗脸",
        "淡斑",
        "烂脸",
        "痘印",
        "痘痘",
        "痤疮",
        "皂基",
        "眼妆",
        "眼影",
        "眼线",
        "眼袋",
        "眼霜",
        "祛斑",
        "祛痘",
        "祛皱",
        "粉刺",
        "美白",
        "美肌",
        "肌肤",
        "腮红",
        "补水",
        "长痘",
        "防晒",
        "除皱",
        "雀斑",
        "面膜",
        "保湿水",
        "化妆刷",
        "化妆棉",
        "化妆水",
        "卸妆水",
        "卸妆油",
        "卸妆膏",
        "卸甲水",
        "去眼袋",
        "去角质",
        "干燥肌",
        "手工皂",
        "抗氧化",
        "抗衰老",
        "抗雾霾",
        "护唇膏",
        "护手霜",
        "护肤品",
        "护肤油",
        "收敛水",
        "敏感肌",
        "柔肤水",
        "柔软水",
        "洁面皂",
        "洁面粉",
        "洗面奶",
        "润唇膏",
        "淡痘印",
        "爽肤水",
        "玻尿酸",
        "珍珠粉",
        "睫毛膏",
        "祛痘印",
        "祛黑头",
        "粉底液",
        "精华油",
        "紧肤水",
        "腮红笔",
        "腮红膏",
        "腮红饼",
        "角质层",
        "身体乳",
        "遮瑕膏",
        "防晒棒",
        "防晒霜",
        "隔离霜",
        "黑眼圈",
        "维生素C",
        "保湿面膜",
        "固体散粉",
        "土豆面膜",
        "收敛毛孔",
        "无油面霜",
        "晒后修复",
        "毛孔粗大",
        "氨基酸基",
        "洁面泡沫",
        "液体散粉",
        "淡斑精华",
        "清洁面膜",
        "皮肤保养",
        "皮肤护理",
        "皮肤清洁",
        "盒装面膜",
        "眼唇卸妆",
        "眼部护理",
        "眼部护肤",
        "睡眠面膜",
        "美容养颜",
        "美容护肤",
        "美白精华",
        "美白面膜",
        "脸部清洁",
        "膜状面膜",
        "芦荟面膜",
        "补水喷雾",
        "补水面膜",
        "闭口粉刺",
        "防晒喷雾",
        "面部卸妆",
        "抗衰老精华",
        "淡化黑眼圈",
        "氨基酸洗面奶"];

(async () => {
    for (let i = 0; i < a.length; i++) {
        let keyword = encodeURIComponent(a[i]);
        let href = "https://search.jd.com/Search?keyword=" + keyword + "&enc=utf-8";

        let html = await getPage(href);
        let d = new jsdom.JSDOM(html);
        let $ = jq(d.window);
        let page = $(".fp-text i")[0].innerHTML;
        await Queue.postDataToMessage("JDTEST", {
                keyword: a[i],
                pageCount: page
        })
        console.log(a[i], page);
    }
})()